# Alembic configuration; the database URL comes from MYBOXI_SERVER_DATABASE_URL (see settings.py).
[alembic]
script_location = %(here)s/migrations
file_template = %%(year)d%%(month).2d%%(day).2d_%%(rev)s_%%(slug)s
prepend_sys_path = .
path_separator = os

[loggers]
keys = root

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = WARNING
handlers =
