"""initial schema (SPEC §3)

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 14:28:28.587117
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), server_default='de-AT', nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index('uq_app_user_email_lower', 'app_user', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('rate_limit',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start', name=op.f('pk_rate_limit'))
    )
    op.create_table('tenant',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan', sa.Enum('self_hosted', 'hosted_free', 'hosted_paid', name='tenant_plan'), server_default='self_hosted', nullable=False),
    sa.Column('config_rev', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant'))
    )
    op.create_table('asset',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_asset_sha256_format')),
    sa.CheckConstraint('bytes >= 0', name=op.f('ck_asset_bytes_nonneg')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_asset_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_asset_tenant_id_id')),
    sa.UniqueConstraint('tenant_id', 'sha256', name=op.f('uq_asset_tenant_id_sha256'))
    )
    op.create_index(op.f('ix_asset_sha256'), 'asset', ['sha256'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('hw_model', sa.Text(), nullable=False),
    sa.Column('agent_version', sa.Text(), nullable=False),
    sa.Column('secret_hash', sa.Text(), nullable=True),
    sa.Column('auth_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('device_rev', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reported', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mqtt_provisioned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_device_tenant_id_tenant'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_device_tenant_id_id'))
    )
    op.create_table('invitation',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'contributor', 'viewer', name='member_role'), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['app_user.id'], name=op.f('fk_invitation_invited_by_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_invitation_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitation_token_hash'))
    )
    op.create_index('uq_invitation_open_email', 'invitation', ['tenant_id', sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.create_table('membership',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'contributor', 'viewer', name='member_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_membership_tenant_id_tenant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_membership_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id', name=op.f('pk_membership'))
    )
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('token',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("uid ~ '^([0-9A-F]{2}){4,10}$'", name=op.f('ck_token_uid_format')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_token_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_token_tenant_id_id')),
    sa.UniqueConstraint('tenant_id', 'uid', name=op.f('uq_token_tenant_id_uid'))
    )
    op.create_table('web_session',
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('csrf_token', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_tenant_id'], ['tenant.id'], name=op.f('fk_web_session_active_tenant_id_tenant'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_web_session_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_web_session_token_hash'))
    )
    op.create_index(op.f('ix_web_session_expires_at'), 'web_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_web_session_user_id'), 'web_session', ['user_id'], unique=False)
    op.create_table('content',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('collection', 'podcast', 'spotify', 'stream', name='content_kind'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cover_asset_id', sa.Uuid(), nullable=True),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('rev', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(source) = 'object'", name=op.f('ck_content_source_object')),
    sa.ForeignKeyConstraint(['tenant_id', 'cover_asset_id'], ['asset.tenant_id', 'asset.id'], name=op.f('fk_content_tenant_id_cover_asset_id_asset'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_content_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content')),
    sa.UniqueConstraint('tenant_id', 'id', name=op.f('uq_content_tenant_id_id'))
    )
    op.create_index('ix_content_tenant_kind', 'content', ['tenant_id', 'kind'], unique=False)
    op.create_table('device_config',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('max_volume', sa.SmallInteger(), server_default='55', nullable=False),
    sa.Column('start_volume', sa.SmallInteger(), server_default='35', nullable=False),
    sa.Column('quiet_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sleep_timer_min', sa.Integer(), nullable=True),
    sa.Column('on_token_removed', sa.Enum('pause', 'continue', name='on_token_removed'), server_default='pause', nullable=False),
    sa.Column('locale', sa.Text(), server_default='de-AT', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Europe/Vienna', nullable=False),
    sa.Column('providers_enabled', sa.ARRAY(sa.Text()), server_default=sa.text("ARRAY['local','podcast']::text[]"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("providers_enabled <@ ARRAY['local','podcast','spotify','stream']::text[]", name=op.f('ck_device_config_providers_known')),
    sa.CheckConstraint("quiet_hours IS NULL OR jsonb_typeof(quiet_hours) = 'object'", name=op.f('ck_device_config_quiet_hours_obj')),
    sa.CheckConstraint('max_volume BETWEEN 0 AND 100', name=op.f('ck_device_config_max_volume_range')),
    sa.CheckConstraint('sleep_timer_min IS NULL OR sleep_timer_min > 0', name=op.f('ck_device_config_sleep_timer_pos')),
    sa.CheckConstraint('start_volume BETWEEN 0 AND 100', name=op.f('ck_device_config_start_volume_range')),
    sa.ForeignKeyConstraint(['tenant_id', 'device_id'], ['device.tenant_id', 'device.id'], name=op.f('fk_device_config_tenant_id_device_id_device'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_device_config_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_device_config'))
    )
    op.create_table('event',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('device_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('boot_id', sa.Uuid(), nullable=True),
    sa.Column('mono_ms', sa.BigInteger(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('token_unknown','token_played','playback_error','storage_full','sync_error','resume_position')", name=op.f('ck_event_type_known')),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_event_device_id_device'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_event_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'id', name=op.f('pk_event'))
    )
    op.create_index(op.f('ix_event_received_at'), 'event', ['received_at'], unique=False)
    op.create_index('ix_event_tenant_type_received', 'event', ['tenant_id', 'type', 'received_at'], unique=False)
    op.create_table('pairing',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('poll_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('hw_model', sa.Text(), nullable=False),
    sa.Column('agent_version', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('device_name', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[0-9]{6}$'", name=op.f('ck_pairing_code_format')),
    sa.ForeignKeyConstraint(['claimed_by'], ['app_user.id'], name=op.f('fk_pairing_claimed_by_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_pairing_device_id_device'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_pairing_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pairing')),
    sa.UniqueConstraint('poll_token_hash', name=op.f('uq_pairing_poll_token_hash'))
    )
    op.create_index(op.f('ix_pairing_device_id'), 'pairing', ['device_id'], unique=False)
    op.create_index('uq_pairing_open_code', 'pairing', ['code'], unique=True, postgresql_where=sa.text('claimed_at IS NULL AND invalidated_at IS NULL'))
    op.create_table('resume_position',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('position_ms', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('item_index >= 0 AND position_ms >= 0', name=op.f('ck_resume_position_nonneg')),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_resume_position_device_id_device'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'token_id'], ['token.tenant_id', 'token.id'], name=op.f('fk_resume_position_tenant_id_token_id_token'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_resume_position_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'token_id', name=op.f('pk_resume_position'))
    )
    op.create_table('binding',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('resume', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('shuffle', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('repeat', sa.Enum('off', 'all', 'one', name='repeat_mode'), server_default='off', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'content_id'], ['content.tenant_id', 'content.id'], name=op.f('fk_binding_tenant_id_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id', 'token_id'], ['token.tenant_id', 'token.id'], name=op.f('fk_binding_tenant_id_token_id_token'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_binding_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id', name=op.f('pk_binding'))
    )
    op.create_index('ix_binding_tenant_content', 'binding', ['tenant_id', 'content_id'], unique=False)
    op.create_table('content_item',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_ms >= 0', name=op.f('ck_content_item_duration_nonneg')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_content_item_position_nonneg')),
    sa.ForeignKeyConstraint(['tenant_id', 'asset_id'], ['asset.tenant_id', 'asset.id'], name=op.f('fk_content_item_tenant_id_asset_id_asset'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'content_id'], ['content.tenant_id', 'content.id'], name=op.f('fk_content_item_tenant_id_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_content_item_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_item')),
    sa.UniqueConstraint('content_id', 'position', deferrable=True, initially='DEFERRED', name=op.f('uq_content_item_content_id_position'))
    )
    op.create_index('ix_content_item_tenant_asset', 'content_item', ['tenant_id', 'asset_id'], unique=False)
    op.create_table('upload',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.Text(), nullable=False),
    sa.Column('source_bytes', sa.BigInteger(), nullable=False),
    sa.Column('tmp_path', sa.Text(), nullable=True),
    sa.Column('profile', sa.Enum('speech', 'music', name='upload_profile'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'duplicate', 'failed', name='upload_status'), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('content_item_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_upload_created_by_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id', 'content_id'], ['content.tenant_id', 'content.id'], name=op.f('fk_upload_tenant_id_content_id_content'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_upload_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload'))
    )
    op.create_index('ix_upload_tenant_content_status', 'upload', ['tenant_id', 'content_id', 'status'], unique=False)
    op.create_index('ix_upload_tenant_source', 'upload', ['tenant_id', 'source_sha256', 'profile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upload_tenant_source', table_name='upload')
    op.drop_index('ix_upload_tenant_content_status', table_name='upload')
    op.drop_table('upload')
    op.drop_index('ix_content_item_tenant_asset', table_name='content_item')
    op.drop_table('content_item')
    op.drop_index('ix_binding_tenant_content', table_name='binding')
    op.drop_table('binding')
    op.drop_table('resume_position')
    op.drop_index('uq_pairing_open_code', table_name='pairing', postgresql_where=sa.text('claimed_at IS NULL AND invalidated_at IS NULL'))
    op.drop_index(op.f('ix_pairing_device_id'), table_name='pairing')
    op.drop_table('pairing')
    op.drop_index('ix_event_tenant_type_received', table_name='event')
    op.drop_index(op.f('ix_event_received_at'), table_name='event')
    op.drop_table('event')
    op.drop_table('device_config')
    op.drop_index('ix_content_tenant_kind', table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_web_session_user_id'), table_name='web_session')
    op.drop_index(op.f('ix_web_session_expires_at'), table_name='web_session')
    op.drop_table('web_session')
    op.drop_table('token')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index('uq_invitation_open_email', table_name='invitation', postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.drop_table('invitation')
    op.drop_table('device')
    op.drop_index(op.f('ix_asset_sha256'), table_name='asset')
    op.drop_table('asset')
    op.drop_table('tenant')
    op.drop_table('rate_limit')
    op.drop_index('uq_app_user_email_lower', table_name='app_user')
    op.drop_table('app_user')
    for enum_name in ('upload_status', 'upload_profile', 'repeat_mode', 'content_kind',
                      'on_token_removed', 'member_role', 'tenant_plan'):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
